/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasgen;
import java.awt.Color;
import java.awt.datatransfer.*;
import java.awt.Toolkit;
import java.util.TimerTask;
import javax.swing.JOptionPane;
/**
 *
 * @author stanislaw
 */
public class Frame extends javax.swing.JFrame {
    int numberOfCharacters = 0, complexity;
    String key;
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PasGen");
        setBackground(new java.awt.Color(0, 153, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("кількість символів");

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("ЗГЕНЕРУВАТИ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "легкий", "середній", "важкий" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.setSelectedItem(1);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("складність");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("----");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setToolTipText("");

        jButton2.setText("?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        complexity = jComboBox1.getSelectedIndex();
//        System.out.println("_------------");
        switch (complexity) {
            case 0:
                key = numberOfCharacters > 0 ? easyKeyGen(numberOfCharacters) : easyKeyGen(4);
                break;
            case 1:
                key = numberOfCharacters > 0 ? middleKeyGen(numberOfCharacters) : middleKeyGen(8);
                break;
            case 2:
                key = numberOfCharacters > 0 ? hardKeyGen(numberOfCharacters) : hardKeyGen(12);
                break;    
        }
        jLabel3.setText(key);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public String easyKeyGen(int complexity) {
        String letters[] = {"a","e","i","o","u","y", "b","c","d","f","g","h","j","k","l","m","n","p","q","r","s","t","v","w","x","z"};
        int L;
        String word = new String();
        
        for (int i = 0; i < complexity; i++) {
            L = Math.toIntExact(Math.round(Math.random()*(letters.length-1)));
            word += letters[L];
            
        }
//        System.out.println(word);
        return word;
    } 
    
    public String middleKeyGen(int complexity) {
        String letters[] = {"a","e","i","o","u","y", "b","c","d","f","g","h","j","k","l","m","n","p","q","r","s","t","v","w","x","z"};
        String lettersBig[] = {"A","E","I","O","U","Y", "B","C","D","F","G","H","J","K","L","M","N","P","Q","R","S","T","V","W","X","Z"};
        String number[] = {"0","1","2","3","4","5","6","7","8","9"};
        int L, b = 0, n = 0;
        String word = new String();
        
        for (int i = 0; i < complexity; i++) {
            L = Math.toIntExact(Math.round(Math.random()*2));
            if (b == 0 && i == complexity - 2) {
                L = 1;
//                System.out.println("b = 0");
            } 
            if (n == 0 && i == complexity-1) {
                L = 2;
//                System.out.println("n = 0");
            }
            
            switch (L) {
                case 0:
                    L = Math.toIntExact(Math.round(Math.random()*(letters.length-1)));
                    word += letters[L];
                    break;
                case 1:
                    L = Math.toIntExact(Math.round(Math.random()*(lettersBig.length-1)));
                    word += lettersBig[L];
                    b++;
                    break;
                default:
                    L = Math.toIntExact(Math.round(Math.random()*(number.length-1)));
                    word += number[L];
                    n++;
                    break;
            }
            
        }
//        System.out.println(word);
        return word;
    } 
    
    public String hardKeyGen(int complexity) {
        String letters[] = {"a","e","i","o","u","y", "b","c","d","f","g","h","j","k","l","m","n","p","q","r","s","t","v","w","x","z"};
        String lettersBig[] = {"A","E","I","O","U","Y", "B","C","D","F","G","H","J","K","L","M","N","P","Q","R","S","T","V","W","X","Z"};
        String number[] = {"0","1","2","3","4","5","6","7","8","9"};
        String characters[] = {"-",".","_","!","?","(",")"};
        int L, b = 0, n = 0, c = 0;
        String word = new String();
        
        for (int i = 0; i < complexity; i++) {
            L = Math.toIntExact(Math.round(Math.random()*3));
            if (b == 0 && i == complexity - 3) {
                L = 1;
//                System.out.println("b = 0");
            } 
            
            if (n == 0 && i == complexity-1) {
                L = 2;
//                System.out.println("n = 0");
            }
            
            if (c == 0 && i == complexity-2) {
                L = 3;
//                System.out.println("c = 0");
            }
            
            switch (L) {
                case 0:
                    L = Math.toIntExact(Math.round(Math.random()*(letters.length-1)));
                    word += letters[L];
                    break;
                case 1:
                    L = Math.toIntExact(Math.round(Math.random()*(lettersBig.length-1)));
                    word += lettersBig[L];
                    b++;
                    break;
                case 2:
                    L = Math.toIntExact(Math.round(Math.random()*(number.length-1)));
                    word += number[L];
                    n++;
                    break;
                default:
                    L = Math.toIntExact(Math.round(Math.random()*(characters.length-1)));
                    word += characters[L];
                    c++;
                    break;
            }
        }
//        System.out.println(word);
        return word;
    } 
    

    
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String s = jTextField1.getText(), f = "";
        int max = 35, min = 4;
        for (int i = min; i <= max; i++) {
            if (s.equals(""+i)) {
                numberOfCharacters = i;
                jTextField1.setBackground(Color.white);
                break;
            } else {
                jTextField1.setBackground(Color.red);
            }
        }
        
        for (int i = 0; i < numberOfCharacters; i++) {
            f = f + "-";
        }
        jLabel4.setText("");
        key = null;
        jLabel3.setText(f);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        try {
        if (key.length()>0) {
            String myString = key;
            StringSelection stringSelection = new StringSelection(myString);
            Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
            clpbrd.setContents(stringSelection, null);
            jLabel4.setText("Пароль зкопійовано до буферу обміну");
            new java.util.Timer().schedule(
                new TimerTask() {
                    public void run() {
                      jLabel4.setText("");  
                    }
                }, 
            2000 );
        } 
        } catch (NullPointerException e) {
            
        }
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JOptionPane.showOptionDialog(null, "Щоб згенерувати пароль потрібно:"
                + "                         \n    Ввести потрібну кількість символів"
                + "                         \n * Вибрати рівен складності "
                + "                         \n * Натиснути кнопку 'ЗГЕНЕРУВАТИ'"
                + "                         \n\n Мінімальна кількість символів - 4, максимальна - 35"
                + "                         \n Скопіювати пароль можна натиснувши на нього лівою кнопкою миші", 
                                    "Help", JOptionPane.CLOSED_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
